In [1]:
import itertools
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import numpy as np
import matplotlib.ticker as ticker
from sklearn import preprocessing
%matplotlib inline

In [2]:
df = pd.read_csv('winequality-white.csv')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [3]:
df['quality'].value_counts() # no of instances in each value

6    2198
5    1457
7     880
8     175
4     163
3      20
9       5
Name: quality, dtype: int64

In [4]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [5]:
X=df[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol']].values

In [6]:
y = df['quality'].values

In [22]:
#preprocessing for knn algorithm
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float)) # we standardize the data i.e. center it around zero
X[0:5]

array([[ 1.72096961e-01, -8.17699008e-02,  2.13280202e-01,
         2.82134917e+00, -3.53550004e-02,  5.69931577e-01,
         7.44565035e-01,  2.33151201e+00, -1.24692128e+00,
        -3.49184257e-01, -1.39315246e+00],
       [-6.57501128e-01,  2.15895632e-01,  4.80011213e-02,
        -9.44765273e-01,  1.47747079e-01, -1.25301866e+00,
        -1.49684624e-01, -9.15417164e-03,  7.40028640e-01,
         1.34184656e-03, -8.24275678e-01],
       [ 1.47575110e+00,  1.74519434e-02,  5.43838363e-01,
         1.00282190e-01,  1.93522599e-01, -3.12141119e-01,
        -9.73335626e-01,  3.58664800e-01,  4.75101984e-01,
        -4.36815783e-01, -3.36667007e-01],
       [ 4.09124986e-01, -4.78657278e-01, -1.17277959e-01,
         4.15768217e-01,  5.59726758e-01,  6.87541270e-01,
         1.12109121e+00,  5.25855242e-01,  1.14803354e-02,
        -7.87341887e-01, -4.99203231e-01],
       [ 4.09124986e-01, -4.78657278e-01, -1.17277959e-01,
         4.15768217e-01,  5.59726758e-01,  6.87541270e-01,
  

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)
X_train.shape,X_test.shape

((3918, 11), (980, 11))

In [12]:
# training the network
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

In [16]:
Ks = 400
mean_acc = np.zeros((Ks-1))
std_acc = np.zeros((Ks-1))
ConfustionMx = [];
for n in range(1,Ks):
    
    #Train Model and Predict  
    neigh = KNeighborsClassifier(n_neighbors = n).fit(X_train,y_train)
    yhat=neigh.predict(X_test)
    mean_acc[n-1] = metrics.accuracy_score(y_test, yhat)

    
    std_acc[n-1]=np.std(yhat==y_test)/np.sqrt(yhat.shape[0])

mean_acc

array([0.64591837, 0.57346939, 0.54591837, 0.54897959, 0.54897959,
       0.53061224, 0.5377551 , 0.54489796, 0.53265306, 0.54285714,
       0.55510204, 0.54795918, 0.54285714, 0.53367347, 0.53469388,
       0.53469388, 0.5244898 , 0.53571429, 0.54183673, 0.53979592,
       0.53877551, 0.54795918, 0.54795918, 0.54795918, 0.54897959,
       0.54591837, 0.5377551 , 0.53673469, 0.53877551, 0.55      ,
       0.54183673, 0.54795918, 0.54795918, 0.55408163, 0.54693878,
       0.55714286, 0.54795918, 0.55408163, 0.54387755, 0.54285714,
       0.53571429, 0.54285714, 0.54489796, 0.53979592, 0.53877551,
       0.54591837, 0.54591837, 0.54489796, 0.54795918, 0.54387755,
       0.54183673, 0.54183673, 0.54081633, 0.5377551 , 0.53979592,
       0.53877551, 0.53979592, 0.5377551 , 0.54387755, 0.54183673,
       0.54489796, 0.54693878, 0.54387755, 0.53877551, 0.54081633,
       0.53673469, 0.53979592, 0.53979592, 0.54081633, 0.53877551,
       0.52959184, 0.52755102, 0.52653061, 0.52653061, 0.52346

# logistic regression

In [24]:
from sklearn.linear_model import LogisticRegression #liblinear is good for small binary classfication datasets
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear')
LR.fit(X_train,y_train)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False)

In [25]:
yhat = LR.predict(X_test)
yhat

array([6, 7, 6, 6, 6, 6, 5, 6, 6, 5, 6, 5, 6, 6, 6, 5, 6, 6, 6, 5, 6, 6,
       5, 6, 6, 6, 5, 6, 5, 5, 5, 6, 5, 5, 5, 6, 6, 5, 5, 6, 6, 5, 6, 6,
       5, 6, 5, 5, 6, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 5, 6, 6, 6,
       6, 5, 6, 5, 5, 6, 5, 5, 6, 6, 6, 6, 6, 6, 5, 5, 6, 6, 6, 6, 5, 6,
       6, 6, 6, 5, 5, 6, 6, 6, 6, 6, 5, 6, 5, 6, 6, 5, 6, 6, 5, 6, 6, 6,
       6, 6, 6, 5, 5, 6, 6, 6, 6, 6, 5, 6, 6, 5, 6, 6, 7, 6, 6, 5, 6, 6,
       6, 6, 5, 6, 6, 5, 6, 5, 6, 6, 6, 5, 6, 5, 5, 6, 5, 6, 6, 6, 6, 6,
       6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6,
       5, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 5, 6, 5, 5, 6, 6, 6, 5, 6, 6, 6,
       5, 6, 6, 5, 6, 6, 6, 6, 7, 6, 6, 6, 5, 6, 6, 6, 5, 6, 5, 5, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 5, 6, 5, 5, 7, 6, 6, 6, 6, 6, 5,
       7, 6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 6, 5, 6, 5,
       6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 5, 6, 6, 6, 5, 5, 6,
       6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 5, 6, 5,

In [26]:
from sklearn.metrics import classification_report
print (classification_report(y_test, yhat))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         5
           4       0.00      0.00      0.00        25
           5       0.58      0.53      0.55       291
           6       0.50      0.80      0.61       432
           7       0.62      0.07      0.12       192
           8       0.00      0.00      0.00        35

   micro avg       0.52      0.52      0.52       980
   macro avg       0.28      0.23      0.21       980
weighted avg       0.51      0.52      0.46       980



C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [27]:
from sklearn.metrics import jaccard_similarity_score #highest accuracy yet
jaccard_similarity_score(y_test, yhat)

0.5224489795918368

# Bayes Classifier

In [9]:
from sklearn.naive_bayes import GaussianNB

In [10]:
wine=GaussianNB()
wine.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [12]:
y_pred=wine.predict(X_test)

In [13]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred, average='weighted') 

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


0.4296734640591677

In [14]:
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred)

0.4387755102040816

In [15]:
from sklearn.metrics import classification_report
print (classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           3       0.14      0.40      0.21         5
           4       0.23      0.24      0.24        25
           5       0.51      0.53      0.52       291
           6       0.52      0.33      0.41       432
           7       0.35      0.64      0.45       192
           8       0.00      0.00      0.00        35
           9       0.00      0.00      0.00         0

   micro avg       0.44      0.44      0.44       980
   macro avg       0.25      0.31      0.26       980
weighted avg       0.46      0.44      0.43       980



C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
